### ISSUE TITLE
5E STATBLOCK IMPORTER: An error has occurred. Please report it using the module link so it can get fixed. 

### ISSUE THREAD

**Issue by StolenVelvet** [jbhaywood/5e-statblock-importer#122] opened 2024-09-08 16:53 UTC
![image](https://github.com/user-attachments/assets/d380bb3c-24a0-485e-b089-acc29f599a40)

Hey there. This is my first time posting on Github so I apologize if any of my formatting or anything isn't proper etiquette. I am also NOT tech savvy at all and have been learning Foundry "the hard way" for the past year or so. 

This is my very first attempt at using Stat Block Importer, I installed and enabled it today, Sep. 8, 2024. It seems like this might be a new and hopefully uncommon issue.

If it matters, my current build of Foundry is Version 11, Build 315. I'm hoping maybe I just need to install an older version of the Stat Block Importer but I have no idea. 

I tried a few different stat blocks including the base format for the Glabrezu that is provided on the main page here and got the same message every time, "5E STATBLOCK IMPORTER: An error has occurred. Please report it using the module link so it can get fixed." 

Console log entries read:

> caught (in promise) TypeError: undefined. Cannot destructure property 'creature' of '(intermediate value)' as it is undefined.
> [Detected 1 package: 5e-statblock-importer]
>     at HTMLButtonElement.<anonymous>

The 3 different texts that I tried are:

> Glabrezu
> Large fiend (demon), chaotic evil
> Armor Class 17 (natural armor)
> Hit Points 157 (15d10 + 75)
> Speed 40 ft.
> STR
> DEX
> CON
> INT
> WIS
> CHA
> 20 (+5) 15 (+2) 21 (+5) 19 (+4) 17 (+3) 16 (+3)
> Saving Throws Str +9, Con +9, Wis +7, Cha +7
> Damage Resistances cold, fire, lightning; bludgeoning,
> piercing, and slashing from nonmagical attacks
> Damage Immunities poison
> Condition Immunities poisoned
> Senses truesight 120 ft., passive Perception 13
> Languages Abyssal, telepathy 120 ft.
> Challenge 9 (5,000 XP)
> Innate Spellcasting. The glabrezu’s spellcasting ability
> is Intelligence (spell save DC 16). The glabrezu can
> innately cast the following spells, requiring no material
> components:
> At will: darkness, detect magic, dispel magic
> 1/day each: confusion, fly, power word stun
> Magic Resistance. The glabrezu has advantage on
> saving throws against spells and other magical effects.
> Actions
> Multiattack. The glabrezu makes four attacks: two with
> its pincers and two with its fists. Alternatively, it makes
> two attacks with its pincers and casts one spell.
> Pincer. Melee Weapon Attack: +9 to hit, reach 10 ft.,
> one target. Hit: 16 (2d10 + 5) bludgeoning damage. If
> the target is a Medium or smaller creature, it is
> grappled (escape DC 15). The glabrezu has two pincers,
> each of which can grapple only one target.
> Fist. Melee Weapon Attack: +9 to hit, reach 5 ft., one
> target. Hit: 7 (2d4 + 2) bludgeoning damage.

---

> Breed Leech
> Tiny aberration (symbiont), neutral evil
> Armor Class 12
> Hit Points 2 (1d4)
> Speed 20 ft.
> STR
> DEX
> CON
> INT
> WIS
> CHA
> 6 (–2)
> 15 (+2)
> 11 (+0)
> 5 (–3)
> 8 (–1)
> 10 (+0)
> Senses blindsight 30 ft. (blind beyond this radius without a host), passive Perception 9
> Languages telepathy (host only)
> Challenge 0 (10 XP)
> Attach. Wondrous item, uncommon (requires attunement)
> While a breed leech is attached to a host, the host regains all expended Hit Dice when they finish a long rest, ignores the first level of exhaustion they would gain in any given 24-hour period, and has advantage on Constitution saving throws to resist disease and being poisoned.
> Curse. If the breed leech is attached to a pregnant humanoid host for at least 24 hours, the child the host is carrying will be born as a daelkyr half-blood. This property of the breed leech is undetectable by divination and it can’t be reversed by magic.
> Symbiotic Nature. A breed leech can't be removed from a host while they’re attuned to it, and the host can't voluntarily end their attunement to it. If the host is targeted by a spell that ends a curse, their attunement to the breed leech ends, and it detaches from the host.
> When a breed leech is detached, it leaves its former host poisoned for 24 hours.
> Actions
> Bite. Melee Weapon Attack: +2 to hit, reach 5 ft., one target. Hit: 1 piercing damage and the target instantly attunes to breed leech as it attaches itself. If the target is already attuned to their maximum limit of magic items, one random attunement is overridden.

---

> Warforged Assassin
> Medium humanoid (warforged), any alignment
> Armor Class 17 (natural armor)
> Hit Points 112 (15d8 + 45)
> Speed 40 ft.
> STR
> DEX
> CON
> INT
> WIS
> CHA
> 8 (–1)
> 19 (+4)
> 16 (+3)
> 15 (+2)
> 15 (+2)
> 11 (+0)
> Saving Throws Dex +7, Wis +5
> Skills Athletics +5, Acrobatics +7, Stealth +10
> Damage Resistances poison
> Senses passive Perception 12
> Languages Common
> Challenge 7 (2,900 XP)
> Warforged Resilience. The warforged has advantage on saving throws against being poisoned and is immune to disease. Magic can't put it to sleep.
> Cunning Action. Once on each of its turns, the warforged can use a bonus action to take the Dash, Disengage, or Hide action.
> Sneak Attack (1/Turn). The warforged deals an extra 17 (5d6) damage when it hits a target with a weapon attack and has advantage on the attack roll, or when the target is within 5 feet of an ally of the warforged that isn't incapacitated and the warforged doesn't have disadvantage on the attack roll.
> Actions
> Multiattack. The warforged makes three weapon attacks.
> Rapier. Melee Weapon Attack: +8 to hit, reach 5ft., one target. Hit: 8 (1d8 + 4) piercing damage.
> Dagger. Melee or Ranged Weapon Attack: +8 to hit, reach 5 ft. or range 20/60 ft., one target. Hit: 6 (1d4 + 4) piercing damage.
> Reactions
> Uncanny Dodge. The warforged assassin takes half damage from an attack that hits it. The warforged must be able to see the attacker.

Let me know if you need anything else, I look forward to seeing this mod in action!

**Comment by StolenVelvet** [comment] 2024-09-09 21:10
UPDATE - It appears that it may just be an issue with Version 11. I installed the last version of the Stat Block available before compatibility with Foundry V12 was added and it's working like a charm.

**Comment by Aioros** [comment] 2024-09-10 08:25
I see, glad you found a way to make it work. I'll reopen this and look into it because that definitely shouldn't be the case, though.

**Comment by cfrench23** [comment] 2024-09-17 23:34
I am having this issue also. Currently running v12 build 329.

**Comment by Aioros** [comment] 2024-09-18 10:58
Thanks for the report and the info. I couldn't reproduce this issue yet, but while I keep looking, could you guys let me know which browser you're using?

**Comment by cfrench23** [comment] 2024-09-18 14:59
I am using chrome,  Version 128.0.6613.138 (Official Build) (64-bit). Here
is a bit more information from the chrome console.

[image: image.png]

**Comment by Aioros** [comment] 2024-09-23 15:01
Do you mind trying the latest unstable version? You would need to install it manually by pasting this manifest URL: https://github.com/Aioros/5e-statblock-importer/releases/download/v1.90.6-3-g98df27a/module.json.

Apart from a few minor changes, it should give a little more information in the console about the error that I would like to see. Appreciate the help in any case, thank you.

**Comment by cfrench23** [comment] 2024-09-23 15:32
Here is the error from the console using the new version.

[image: image.png]

**Comment by Aioros** [comment] 2024-09-23 15:35
Hey, thanks for the quick response, but I don't seem to be able to see the image. Any way you could upload it differently? Otherwise I would also be ok with just a copy/paste of the error from the console.

**Comment by cfrench23** [comment] 2024-09-23 19:21
Try this.

**Comment by Aioros** [comment] 2024-09-23 19:27
Nope, sorry. I think images in comments from emails are not really working. You might need to actually use the webpage here on GitHub for that.

**Comment by cfrench23** [comment] 2024-09-23 19:32
Here you go.

Foundry VTT | Retrieved and compiled template
modules/5e-statblock-importer/templates/sbiWindow.hbs
sbiUtils.js:7 5e Statblock Importer | ERROR: TypeError: line.trim is not a
function
sbiUtils.js:7 5e Statblock Importer | ERROR: TypeError: line.trim is not a
function

**Comment by Aioros** [comment] 2024-09-24 12:34
The newest version of the module has a tentative fix for this issue. Could you try updating to v1.90.7 and see if it works for you?

**Comment by cfrench23** [comment] 2024-09-24 14:53
It works, good job man. I know those bugs can be hard to nail down.

**Closed as completed** 2024-09-24 15:05 UTC
Labels: bug
